jli::dis_import!(add);
jli::dis_import!(init);
jli::dis_import!(list);
jli::dis_import!(create);
jli::dis_import!(update_master);
jli::dis_import!(update);
jli::dis_import!(show);
jli::dis_import!(delete);
jli::dis_import!(update_details);
