com::dis_import!(add_parser);
com::dis_import!(init_parser);
com::dis_import!(list_parser);
com::dis_import!(create_parser);
com::dis_import!(update_master_parser);
com::dis_import!(update_parser);
com::dis_import!(show_parser);
com::dis_import!(delete_parser);
com::dis_import!(update_details_parser);
