[package]
name = "passger"
version = "0.1.0"
edition = "2024"

[dependencies]
jli = { path = "../jli" }
db_manager = { path = "../db_manager" }
com = { path = "../com" }
tabled = "0.20"
ulid = "1.2.1"
arboard = "3.6.1"
rpassword = "7.4.0"
